2024-08-01 12:06:00,628 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-08-01 12:10:00,733 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-08-01 12:14:01,059 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-08-01 12:18:00,275 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-08-01 12:22:00,382 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-10-17 21:26:01,010 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for airticket.localhost
2024-10-17 21:26:01,015 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for airticket.localhost
2024-10-17 21:26:01,032 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for airticket.localhost
2024-10-17 21:26:01,046 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for airticket.localhost
2024-10-17 21:26:01,060 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for airticket.localhost
2024-10-17 21:26:01,063 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for airticket.localhost
2024-10-17 21:26:01,074 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for airticket.localhost
2024-10-17 21:26:01,079 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for airticket.localhost
2024-10-17 21:26:01,081 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for airticket.localhost
2024-10-17 21:26:01,102 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for airticket.localhost
2024-10-17 21:26:01,137 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.localhost
2024-10-17 21:26:01,156 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.localhost
2024-10-17 21:26:01,164 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.localhost
2024-10-17 21:26:01,180 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.localhost
2024-10-17 21:26:01,189 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.localhost
2024-10-21 13:02:00,677 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.localhost
2024-10-21 13:02:00,682 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for mysite.localhost
2024-10-21 13:02:00,685 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for mysite.localhost
2024-10-21 13:02:00,714 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.localhost
2024-10-21 13:02:00,721 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.localhost
2024-10-21 13:02:00,730 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.localhost
2024-10-21 13:02:00,734 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.localhost
2024-10-21 13:02:00,736 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.localhost
2024-10-21 13:02:00,739 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.localhost
2024-10-21 13:02:00,742 ERROR scheduler Skipped queueing frappe.email.doctype.newsletter.newsletter.send_scheduled_email because it was found in queue for mysite.localhost
2024-10-21 13:02:00,744 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for mysite.localhost
2024-10-21 13:02:00,756 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for mysite.localhost
2024-10-21 13:02:00,759 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for mysite.localhost
2024-10-21 13:02:00,762 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for mysite.localhost
2024-10-21 13:02:00,765 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.localhost
2024-10-21 13:02:00,770 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for mysite.localhost
2024-10-21 13:02:00,775 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.localhost
2024-10-21 13:02:00,795 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for doctorappointment.localhost
2024-10-21 13:02:00,804 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for doctorappointment.localhost
2024-10-21 13:02:00,820 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for doctorappointment.localhost
2024-10-21 13:02:00,825 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for doctorappointment.localhost
2024-10-21 13:02:00,829 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for doctorappointment.localhost
2024-10-21 13:02:00,840 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for doctorappointment.localhost
2024-10-21 13:02:00,843 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for doctorappointment.localhost
